[versions]
# https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin = "2.3.10"
# https://github.com/Kotlin/kotlinx.coroutines
kotlinx-coroutines = "1.10.2"
# https://github.com/vanniktech/gradle-maven-publish-plugin
publish = "0.36.0"
# https://github.com/Kotlin/dokka
dokka = "2.1.0"
# https://github.com/smyrgeorge/log4k
log4k = "1.3.2"
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = "1.10.0"
# https://github.com/ktorio/ktor
ktor = "3.4.0"
# https://www.bouncycastle.org
bouncycastle = "1.83"
# https://github.com/ionspin/kotlin-multiplatform-bignum
bignum = "0.3.10"
# https://github.com/InsertKoinIO/koin
koin = "4.1.1"
# https://github.com/smyrgeorge/sqlx4k
sqlx4k = "1.5.20"
# https://github.com/orchestr7/ktoml
ktoml = "0.7.1"
# https://github.com/google/ksp
ksp = "2.3.5"
# https://github.com/arrow-kt/arrow
arrow = "2.2.1.1"

[libraries]
gradle-kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-publish-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }
gradle-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
log4k = { module = "io.github.smyrgeorge:log4k", version.ref = "log4k" }
log4k-slf4j = { module = "io.github.smyrgeorge:log4k-slf4j", version.ref = "log4k" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-resilience = { module = "io.arrow-kt:arrow-resilience", version.ref = "arrow" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
sqlx4k = { module = "io.github.smyrgeorge:sqlx4k", version.ref = "sqlx4k" }
sqlx4k-arrow = { module = "io.github.smyrgeorge:sqlx4k-arrow", version.ref = "sqlx4k" }
sqlx4k-codegen = { module = "io.github.smyrgeorge:sqlx4k-codegen", version.ref = "sqlx4k" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
pubhish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
